version: "3.8"

services:
  customer-service:
    image: alexjuep/transaction-service:v1.0
    container_name: transaction-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka
    depends_on:
      - discovery-service
      - rabbitmq

  discovery-service:
    image: alexjuep/discovery-service:latest
    container_name: discovery-service
    ports:
      - "8761:8761"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
